name: 23f2004462@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '0 0 1 * *'  

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: 23f2004462@ds.study.iitm.ac.in
      run: |
        date > date.txt
        git config --global user.name "Aadhi-code4"
        git config --global user.email "aadhilingam57910@gmail.com"
        git add date.txt
        git commit -m "Daily commit $(date)"
        git push https://github.com/${{ secrets.ACTIONS_PAT }}:x-oauth-basic@github.com/Aadhi-code4/Scraping_with_GitHub-Actions.git
