name: Daily_Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs the workflow daily at 00:00 UTC

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make a Commit by school@gmail.com
      run: |
        date > date.txt
        git config --global user.name "YOUR_GITHUB_USERNAME"  # Replace with your GitHub username
        git config --global user.email "aadhi..@gmail.com"   # Replace with your email
        git add date.txt
        git commit -m "Daily commit $(date)"
        git push
