name: Daily_Commit

on:
  schedule:
    - cron: '*/5 * * * *'  

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Make a Commit by 23f2004462@ds.study.iitm.ac.in
      run: |
        date > date.txt
        git config --global user.name "Aadhi-code4"
        git config --global user.email "aadhilingam57910@gmail.com"
        git add date.txt
        git commit -m "Daily commit $(date)"
        git push
